# Generated by Django 4.0.3 on 2022-03-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EsEntregable',
            new_name='Entregable',
        ),
    ]
